### ISSUE TITLE
Example workflow doesn't work

### ISSUE THREAD

**Issue by itstommymorgan** [joshnesbitt/project#1]
A ruby script can't change the directory of its parent process (the shell, in this case) by using %x (or system, for that matter). So a default workflow of `cd %path` will execute just fine, but have no effect.

Not entirely certain of the way to fix this.

**Comment by joshnesbitt** [comment]
Hmmm. To be honest I never really wanted the commands to execute within the context of the parent shell as running in a subshell would enable you to continue working as you were within the parent shell. I do however see how this behaviour could be beneficial though. Any ideas on how this could be done? I'll have a dig around and see. Thanks for reporting!

**Comment by joshnesbitt** [comment]
It would also be really useful to see shell state to be preserved between workflow items too, but stringing them all into one long command isn't the solution.

**Comment by itstommymorgan** [comment]
There's another issue, too, in that each use of %x[ ] will create it's own subshell.

e.g.:

```
%x[ cd %path ]
%x[ pwd ]
```

should demonstrate that any sequence of commands that affect shell variables (like the current working directory) won't have any effect on commands later on down the workflow. So workflows like

```
:default:
  - cd %path
  - rake
```

would also be rendered useless.

The latter could _possibly_ be solved by taking the commands and executing them altogether, rather than individually (e.g. `%x[ cd %path; rake ]`). Still not sure how to solve the issue where somebody simply wants to 'jump' to the project directory, though.

**Comment by itstommymorgan** [comment]
Another possible option: create a shell script in a temporary directory containing all the commands that you then execute and delete.

**Comment by joshnesbitt** [comment]
Almost beat me to it ;) just on my phone at the moment but will definitely take a look at this when I get back, it's quite a big blocker for creating better workflows.

**Comment by joshnesbitt** [comment]
After looking around it seems that no matter how the problem is approached in Ruby, the effect might still be the same. Child processes cannot alter the parent processes state. One option would be to wrap the gem within a bash script so we have more control over the running process. Or maybe going against what I said above I could look for common commands (such as cd) and use the Ruby libraries to perform them instead of shelling out.

Any ideas?

**Comment by itstommymorgan** [comment]
If you don't want it to affect the parent shell, then the best thing to do (I think) is still to dump the commands out to a temporary shell script that gets executed.

If you want it to be _able_ to affect the parent shell, that would have to involve creating a shell function.

**Comment by joshnesbitt** [comment]
In what cases would creating a temp script be more beneficial over just chaining the commands? I might opt to not affect the parent shell for now but will look into it in the future.

**Comment by itstommymorgan** [comment]
Well, if memory serves, most shells have some sort of a command line length limit. So any sufficiently advanced workflow wouldn't work if you tried to chain it together. I'd have to do a bit of research to determine what constitutes 'sufficiently advanced,' though. It could be that it's large enough to be of no concern.

**Comment by joshnesbitt** [comment]
Sure, let me know if you find anything, otherwise I'll probably go down that route now whilst looking for a more elegant fix.
