### ISSUE TITLE
Workflow steps are not independent.

### ISSUE THREAD

**Issue by devemouse** [joshnesbitt/project#7]
I have following settings:

```
:workflows:
 :default:
   - gvim %path
   - cd %path && git st

:projects:
 :projectA:
  :path: /a//valid/path/
  :workflow: default
```

And when I exeute:

```
project projectA
```

the script launches gvim but waits for it to be closed before executing cd command.

**Comment by joshnesbitt** [comment]
Thanks for reporting this. This is similar to #5 where a command within a workflow does not exit correctly to allow the next to continue. In the case of GVim I don't think daemonising the command would help at all, as it needs to be in the foreground for you to use GVim (as far as I understand). I need to figure out a way to handle this type of behaviour.

**Comment by joshnesbitt** [comment]
Closing as a duplicate.
